apiVersion: v1
kind: Pod
metadata:
  name: k5wang-login
spec:
  containers:
  - name: vol-container
    image: gitlab-registry.nautilus.optiputer.net/vamsirk/research-containers
    command: ["/bin/bash"]
    args: ["-c", "sleep infinity"]
    resources:
      requests:
        memory: "12Gi"
        cpu: "1"
        nvidia.com/gpu: "1"
      limits:
        memory: "12Gi"
        cpu: "1"
        nvidia.com/gpu: "1"
    volumeMounts:
    - name: local
      mountPath: /local
    - name: k5wang-volume     #use your own volume path
      mountPath: /k5wang-volume
    - name: k5wang-volume-datasets
      mountPath: /k5wang-volume-datasets
  restartPolicy: Never
  volumes:
    - name: local
      emptyDir: {}
    - name: k5wang-volume
      persistentVolumeClaim:
        claimName: k5wang-volume
    - name: k5wang-volume-datasets
      persistentVolumeClaim:
        claimName: k5wang-volume-datasets
  nodeSelector:
    gpu-type: "1080Ti"
    # gpu-type: "2080Ti"



