apiVersion: batch/v1
kind: Job # Deployment will automatically restart when killed. Use Pod if not needed
metadata:
  # labels:
  #   k8s-app: research
  # generateName: k5wang-job-train     # Name of Job
  name: k5wang-search-pbc-darts-50-off
  namespace: ecepxie
spec:
  template:
    metadata:
      labels:
        name: k5wang-train
    spec:
      restartPolicy: Never
      containers:
      - name: research
        image: gitlab-registry.nautilus.optiputer.net/vamsirk/research-containers
        imagePullPolicy: Always
        workingDir: /local
        command: ["/bin/bash", "/k5wang-volume/Blood_cell_classification_kaggle/cluster/bash/search-PBC-darts-off.sh"]
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
            nvidia.com/gpu: 1
          limits:
            memory: "2Gi"
            cpu: "1"
            nvidia.com/gpu: 1

        volumeMounts:
        - name: k5wang-volume     #use your own volume path
          mountPath: /k5wang-volume
        - name: k5wang-volume-datasets
          mountPath: /k5wang-volume-datasets
        - name: local
          mountPath: /local
    
      volumes:
        - name: k5wang-volume
          persistentVolumeClaim:
            claimName: k5wang-volume
        - name: k5wang-volume-datasets
          persistentVolumeClaim:
            claimName: k5wang-volume-datasets
        - name: local
          emptyDir: {}
      
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gpu-type
                operator: In # Use NotIn for other types
                values: 
                  - 1080Ti
                  # - 2080Ti
                  # - TITANRTX
              - key: nautilus.io/disktype
                operator: In
                values: 
                  - nvme

      # nodeSelector:
      #   gpu-type: "1080Ti"
      #   # gpu-type: "2080Ti"
      #   # gpu-type: "TITANRTX"
      #   nautilus.io/disktype: nvme   

      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: gpu-type
      #           operator: In # Use NotIn for other types
      #           values:
      #           - TITANRTX
