apiVersion: batch/v1
kind: Job # Deployment will automatically restart when killed. Use Pod if not needed
metadata:
  # labels:
  #   k8s-app: research
  # generateName: k5wang-job-train     # Name of Job
  name: k5wang-train-50-300-reorg  # 50 search epochs / 300 train epochs
  namespace: ecepxie
spec:
  template:
    metadata:
      labels:
        name: k5wang-train
    spec:
      restartPolicy: Never
      containers:
      - name: research
        image: gitlab-registry.nautilus.optiputer.net/vamsirk/research-containers
        imagePullPolicy: Always
        workingDir: /local
        # workingDir: /k5wang-volume/Blood_cell_classification_kaggle/cluster  # dir in which code is executed
        
        command: ["/bin/bash", "/k5wang-volume/Blood_cell_classification_kaggle/cluster/bash/train-BC-50-300.sh"]
        
        resources:
          requests:
            memory: "3Gi"
            cpu: "2"
            nvidia.com/gpu: 1
          limits:
            memory: "3Gi"
            cpu: "2"
            nvidia.com/gpu: 1

        volumeMounts:
        - name: local
          mountPath: /local
        - name: k5wang-volume     #use your own volume path
          mountPath: /k5wang-volume
        - name: k5wang-volume-datasets
          mountPath: /k5wang-volume-datasets
    
      volumes:
        - name: local
          emptyDir: {}
        - name: k5wang-volume
          persistentVolumeClaim:
            claimName: k5wang-volume
        - name: k5wang-volume-datasets
          persistentVolumeClaim:
            claimName: k5wang-volume-datasets
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gpu-type
                operator: In # Use NotIn for other types
                values: 
                  # - 1080Ti
                  # - 2080Ti
                  - TITANRTX

