name: k5wang
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2
  - pytorch
  - numba/label/dev
  - conda-forge
  - conda-forge/label/gcc7
  - conda-forge/label/broken
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - soumith
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - defaults
dependencies:
  - cudatoolkit
  - pytorch=1.3.0
  # - pytorch = 0.3.1
  - torchvision
  # - torchvision = 0.2.0
  - pydicom
  - tensorboard=1.14.0
  - tqdm
  - pandas
  - opencv
  - matplotlib

